### ISSUE TITLE
Is there a plan to add support for Swift Package Manager in the near feature?

### ISSUE THREAD

**Issue by r3econ** [keefertaylor/Base58Swift#7]
Xcode 11 takes Swift packages to the level where they are finally fully useable. I think it would be cool to add the support for it.

**Comment by keefertaylor** [comment]
Swift Package Manager feels like something this library could / should support. 

I've been a bit busy lately, but I can certainly add it to my backlog. If you know what you're doing and want to send a PR, I'm also happy to merge / review.

**Comment by keefertaylor** [comment]
Fixed in #9. 

Let me know if you have any problems consuming the package.
